services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: aula-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
